angular.module('computer',['ngRoute'])
.config(['$routeProvider',function($routeProvider){
	$routeProvider
	.when('/main',{
		templateUrl:'main.html',
		controller:'MainCtrl'
	})
	.when('/about',{
		templateUrl:'about.html',
		controller:'MainCtrl'
	})
	.when('/services',{
		templateUrl:'services.html',
		controller:'ServiceCtrl'
	})
	.when('/contact',{
		templateUrl:'contact.html',
		controller:'MainCtrl'
	})
	.otherwise({redirectTo:'/main'})
	;
}])
.controller('MainCtrl',['$scope',function($scope){

}])
.controller('ServiceCtrl',['$scope','$http',function($scope,$http){
	$http.get('services.json').then(function(response){
		$scope.services=response.data;
	},function(response,status){});
}])
;